### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by DirtyF** [mariealine/100-km-jekyll-tailwind#2]
postCSS error on Vercel, not reproduced locally 🤔 

Full log from Vercel
```
17:04:35.234  Retrieving list of deployment files...
17:04:35.444  Downloading 39 deployment files...
17:04:38.502  Installing build runtime...
17:04:38.884  Build runtime installed: 382.486ms
17:04:39.224  Looking up build cache...
17:04:39.257  Build cache not found
17:04:39.751  [DEPRECATED] The `--no-prune` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set no-prune 'true'`, and stop using this flag
17:04:42.221  Fetching gem metadata from https://rubygems.org/..........
17:04:42.243  Using bundler 2.1.4
17:06:55.728  Installing jekyll 4.0.1
17:06:55.791  Bundle complete! 3 Gemfile dependencies, 30 gems now installed.
-------------------------------------------------------------------------------------
17:06:55.938  Installing dependencies...
17:06:56.148  yarn install v1.22.0
17:06:56.172  [1/4] Resolving packages...
17:07:00.837  Done in 4.69s.
17:07:01.716  Configuration file: /zeit/1cdb6b08/_config.yml
17:07:02.278              Source: /zeit/1cdb6b08
17:07:02.278         Destination: /zeit/1cdb6b08/_site
17:07:02.278   Incremental build: disabled. Enable with --incremental
17:07:02.279        Generating... 
17:07:02.279  PostCSS Server listening on port 8124...
17:07:04.718  /zeit/1cdb6b08/node_modules/purgecss/lib/purgecss.js:512
17:07:04.718              throw _iteratorError;
17:07:04.718              ^
17:07:04.718  CssSyntaxError: <css input>:92823:175: Unclosed string
17:07:04.718      at Input.error (/zeit/1cdb6b08/node_modules/postcss/lib/input.js:130:16)
17:07:04.718      at unclosed (/zeit/1cdb6b08/node_modules/postcss/lib/tokenize.js:50:17)
17:07:04.718      at Object.nextToken (/zeit/1cdb6b08/node_modules/postcss/lib/tokenize.js:159:15)
17:07:04.718      at Parser.other (/zeit/1cdb6b08/node_modules/postcss/lib/parser.js:153:30)
17:07:04.718      at Parser.parse (/zeit/1cdb6b08/node_modules/postcss/lib/parser.js:77:16)
17:07:04.718      at Function.parse (/zeit/1cdb6b08/node_modules/postcss/lib/parse.js:17:12)
17:07:04.718      at Purgecss.getCssContents (/zeit/1cdb6b08/node_modules/purgecss/lib/purgecss.js:481:31)
17:07:04.718      at Purgecss.purge (/zeit/1cdb6b08/node_modules/purgecss/lib/purgecss.js:446:19)
17:07:04.718      at Object.<anonymous> (/zeit/1cdb6b08/node_modules/purgecss/bin/purgecss:71:41)
17:07:04.718      at Module._compile (internal/modules/cjs/loader.js:955:30) {
17:07:04.718    name: 'CssSyntaxError',
17:07:04.718    reason: 'Unclosed string',
...
17:07:04.862  Error: Command "jekyll build" exited with 1
17:07:06.922  Done with "package.json"
```

**Comment by DirtyF** [comment]
Issue opened on https://github.com/mhanberg/jekyll-postcss/issues/12

**Comment by DirtyF** [comment]
The error on Vercel is now fixed, I only get the error locally.
